import os
import json
from datetime import datetime

class FinOpsReporter:
    """
    Tracks agent actions, calculates estimated cost savings, 
    and exports JSON audit logs and Markdown reports.
    """
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        self.audit_log = []
        self.total_savings_usd = 0.0

    def log_action(self, tool_name: str, args: dict, result: dict, status: str):
        """Records an individual tool execution entry."""
        entry = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "tool": tool_name,
            "arguments": args,
            "status": status,
            "result": result
        }
        self.audit_log.append(entry)

        # Track potential monthly cost savings on deletion/remediation
        if tool_name == "delete_azure_resource" and status == "EXECUTED":
            res_type = args.get("resource_type", "")
            if res_type == "disk":
                self.total_savings_usd += 1.60  # Default benchmark cost for test disks
            elif res_type == "public_ip":
                self.total_savings_usd += 3.60  # Default benchmark cost for unassigned IPs

    def export_reports(self, subscription_id: str, mode: str):
        """Generates both JSON and Markdown report artifacts."""
        timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # 1. Export JSON Audit Log
        json_filename = os.path.join(self.output_dir, f"finops_audit_{timestamp_str}.json")
        json_data = {
            "subscription_id": subscription_id,
            "execution_mode": mode,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "estimated_monthly_savings_usd": round(self.total_savings_usd, 2),
            "audit_trail": self.audit_log
        }
        
        with open(json_filename, "w") as f:
            json.dump(json_data, f, indent=2)

        # Also write to latest JSON pointer
        with open(os.path.join(self.output_dir, "audit_latest.json"), "w") as f:
            json.dump(json_data, f, indent=2)

        # 2. Export Markdown Summary Report
        md_filename = os.path.join(self.output_dir, f"finops_report_{timestamp_str}.md")
        md_content = self._generate_markdown(subscription_id, mode)

        with open(md_filename, "w") as f:
            f.write(md_content)

        # Also write to latest Markdown pointer
        with open(os.path.join(self.output_dir, "report_latest.md"), "w") as f:
            f.write(md_content)

        print("\n" + "="*50)
        print("📊 FINOPSSENTINEL REPORT GENERATED")
        print("="*50)
        print(f"📁 JSON Audit Log : {json_filename}")
        print(f"📝 Markdown Report: {md_filename}")
        print(f"💰 Estimated Monthly Savings: ${round(self.total_savings_usd, 2)} USD")
        print("="*50 + "\n")

    def _generate_markdown(self, subscription_id: str, mode: str) -> str:
        """Helper to build a styled Markdown report."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"""# 🛡️ FinOpsSentinel - Cloud Audit & Remediation Summary

**Date:** {now}  
**Subscription ID:** `{subscription_id}`  
**Execution Mode:** `{mode}`  
**Projected Monthly Savings:** **${round(self.total_savings_usd, 2)} USD**

---

## 📑 Action Log Details

| Timestamp (UTC) | Tool Name | Target Resource / Arguments | Execution Status |
| :--- | :--- | :--- | :--- |
"""
        for item in self.audit_log:
            ts = item['timestamp'].split('T')[1][:8]
            tool = item['tool']
            status = item['status']
            args = json.dumps(item['arguments'])
            
            status_badge = "✅ EXECUTED" if status == "EXECUTED" else f"⚠️ {status}"
            md += f"| `{ts}` | `{tool}` | `{args}` | {status_badge} |\n"

        md += """
---
*Report auto-generated by FinOpsSentinel Autonomous Cloud AI Agent.*
"""
        return md